# Generated by Django 5.0.2 on 2024-02-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_exceldata_user_userpassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_send",
            field=models.BooleanField(default=False, verbose_name="Email Send"),
        ),
    ]
