# Generated by Django 5.0.2 on 2024-02-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_email_send"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("N", "Prefer Not to Say")],
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AddField(
            model_name="userrequest",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("N", "Prefer Not to Say")],
                max_length=10,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
