# Generated by Django 5.0.2 on 2024-02-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_daywise_criteria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daywise_criteria",
            field=models.TextField(
                default="{1: 1, 2: 1, 3: 1}",
                verbose_name="daywise_Criteria JSON (DONT FILL THIS)",
            ),
        ),
    ]
