# Generated by Django 5.0.2 on 2024-03-01 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_daywise_criteria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrequest",
            name="captain",
        ),
        migrations.RemoveField(
            model_name="userrequest",
            name="captain_paid",
        ),
        migrations.AddField(
            model_name="participation",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captain",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="captain_paid",
            field=models.BooleanField(default=False, verbose_name="captain paid"),
        ),
        migrations.AlterField(
            model_name="user",
            name="criteria",
            field=models.TextField(
                default='{"C": 0, "T": 0, "S": 0}',
                verbose_name="Criteria JSON (DONT FILL THIS)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="daywise_criteria",
            field=models.TextField(
                default='{"1": 0, "2": 0, "3": 0}',
                verbose_name="daywise_Criteria JSON (DONT FILL THIS)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Comp A", "Computer A"),
                    ("Comp B", "Computer B"),
                    ("IT", "IT"),
                    ("EXTC", "EXTC"),
                    ("Mech A", "Mechanical A"),
                    ("Mech B", "Mechanical B"),
                    ("Elec", "Electrical"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                null=True,
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="userrequest",
            name="department",
            field=models.CharField(
                choices=[
                    ("Comp A", "Computer A"),
                    ("Comp B", "Computer B"),
                    ("IT", "IT"),
                    ("EXTC", "EXTC"),
                    ("Mech A", "Mechanical A"),
                    ("Mech B", "Mechanical B"),
                    ("Elec", "Electrical"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                verbose_name="Department",
            ),
        ),
    ]
