# Generated by Django 5.0.2 on 2024-02-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_auto_20230122_2024"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image_googledrive",
            field=models.URLField(
                blank=True, null=True, verbose_name="Image Google Drive"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[("C", "Cultural"), ("T", "Technical"), ("S", "Sports")],
                max_length=1,
                verbose_name="Category",
            ),
        ),
    ]
