# Generated by Django 5.0.2 on 2024-02-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_image_googledrive_alter_event_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Club Name")),
                ("description", models.TextField(verbose_name="Club Description")),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clubevent",
                to="events.club",
            ),
            preserve_default=False,
        ),
    ]
