# Generated by Django 5.0.2 on 2024-03-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_club_event_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_seminar_department",
            field=models.BooleanField(
                default=False, verbose_name="Is Event a Seminar of Department"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="seminar_branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Comp", "Computer"),
                    ("IT", "IT"),
                    ("EXTC", "EXTC"),
                    ("Mech", "Mechanical"),
                    ("Elec", "Electrical"),
                    ("OTHER", "Other"),
                ],
                max_length=125,
                verbose_name="Seminar Branch",
            ),
        ),
    ]
