# Generated by Django 5.0.2 on 2024-03-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_event_is_seminar_department_event_seminar_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[("C", "Cultural"), ("T", "Technical"), ("S", "seminar\xa0")],
                max_length=1,
                verbose_name="Category",
            ),
        ),
    ]
